### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by yoid2000**

### CODE REVIEW

**Comment by cristianberneanu** [comment]
Paul, there is already a license in the `LICENSE.md` file (a BSL/PostgreSQL license).

**Comment by yoid2000** [comment]
Yes. I want to change out to MIT

**Comment by cristianberneanu** [comment]
Then please remove the original one, otherwise the repository will be left with two license files.

**Comment by yoid2000** [comment]
Ok, old license has been removed

**Review by cristianberneanu — APPROVED** [review]

**Review by edongashi — APPROVED** [review]
I would keep the same file name, in case the release process expects it.

**Pull request merged**
